# Generated by Django 4.1.4 on 2023-03-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['createdAt']},
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='postalCode',
            new_name='postalcode',
        ),
    ]
