# Generated by Django 4.1.4 on 2023-03-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
