# Generated by Django 4.1.4 on 2023-03-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_order_shippingprice_alter_order_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shippingPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
