# Generated by Django 4.1.4 on 2023-03-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_order_shippingprice_alter_order_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='receiver',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
