# Generated by Django 4.1.4 on 2023-03-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='GettyImages_1177471633.jpg', null=True, upload_to='product/None'),
        ),
    ]
